Add git fetch to updating galaxy instruction
Otherwise if the release branch doesn't exist the checkout fails with:
```
$ git checkout bla
error: pathspec 'bla' did not match any file(s) known to git.
```